### ISSUE TITLE
Está funcionando?

### ISSUE THREAD

**Issue by prem-prakash** [brunoosilva/moip-sdk-js#1]
Tentei usar e tá dando sempre que o hash é inválido.

Também não consigo usar o método isValid

CreditCard.isValid(creditCard)

**Comment by brunoosilva** [comment]
Qual erro é gerado ?

**Comment by rafaneri** [comment]
@brunoosilva, da uma olhada nessa [issue](https://github.com/moip/moip-sdk-php/issues/217).

**Comment by prem-prakash** [comment]
@rafaneri tem a ver com os parâmetros de encriptação da lib NodeRSA

Cheguei a fazer um PR para resolver:

https://github.com/brunoosilva/moip-sdk-js/pull/4#issuecomment-351590358

CC @brunoosilva

**Comment by rafaneri** [comment]
@prem-prakash fiz a alteração na pasta dist como foi sugerido:

```javascript
var rsakey = new _nodeRsa2.default(this.pubKey, { encryptionScheme: 'pkcs1' });
```
mas ainda sem sucesso. O seu fork está funcionando na sandbox?

**Comment by rafaneri** [comment]
Estava com um pequeno erro na minha public key, ajustei e mantive o encryptionScheme e deu certo.
valeu @prem-prakash!

**Comment by brunoosilva** [comment]
Resolvido com o PR https://github.com/brunoosilva/moip-sdk-js/pull/5
